language: cpp
sudo: true

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_VERSION="3.10.0"
    - GTEST_VERSION="1.8"

cache:
  directories:
    - ${DEPS_DIR}/cmake-${CMAKE_VERSION}

matrix:
  include:
    # GCC supported versions gcc6, gcc7, gcc8
    - env: GCC_VERSION=6 BUILD_TYPE=Debug CPPSTD=14
      os: linux
      addons: &gcc6
        apt:
          packages:
            - g++-6
            - libtbb-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: GCC_VERSION=6 BUILD_TYPE=Release CPPSTD=14
      os: linux
      addons: *gcc6

    - env: GCC_VERSION=7 BUILD_TYPE=Debug CPPSTD=14
      os: linux
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - libtbb-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: GCC_VERSION=7 BUILD_TYPE=Release CPPSTD=14
      os: linux
      addons: *gcc7

    - env: GCC_VERSION=7 BUILD_TYPE=Debug CPPSTD=17
      os: linux
      addons: *gcc7

    - env: GCC_VERSION=7 BUILD_TYPE=Release CPPSTD=17
      os: linux
      addons: *gcc7

    - env: GCC_VERSION=8 BUILD_TYPE=Debug CPPSTD=14
      os: linux
      addons: &gcc8
        apt:
          packages:
            - g++-8
            - libtbb-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: GCC_VERSION=8 BUILD_TYPE=Release CPPSTD=14
      os: linux
      addons: *gcc8

    - env: GCC_VERSION=8 BUILD_TYPE=Debug CPPSTD=17
      os: linux
      addons: *gcc8

    - env: GCC_VERSION=8 BUILD_TYPE=Release CPPSTD=17
      os: linux
      addons: *gcc8

    - env: CLANG_VERSION=3.9 BUILD_TYPE=Release CPPSTD=14
      os: linux
      addons: &clang39
        apt:
          packages:
            - clang-3.9
            - libstdc++-6-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: CLANG_VERSION=4.0 BUILD_TYPE=Release CPPSTD=14
      os: linux
      addons: &clang40
        apt:
          packages:
            - clang-4.0
            - libstdc++-6-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0

    #- env: XCODE_VERSION=9.4 BUILD_TYPE=Release CPPSTD=14
    #  os: osx
    #  osx_image: xcode9.4

    - env: XCODE_VERSION=10.2 BUILD_TYPE=Release CPPSTD=14
      os: osx
      osx_image: xcode10.2


before_install:
  - set -e
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          brew update
          brew install gnu-sed
          brew install gnu-which
          brew upgrade cmake
          export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    fi
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      if [ -f ${DEPS_DIR}/cmake-${CMAKE_VERSION}/cached ]; then
        echo "Using cached cmake version ${CMAKE_VERSION}."
      else
        CMAKE_URL="https://cmake.org/files/v3.10/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake-${CMAKE_VERSION}
        travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake-${CMAKE_VERSION}
        touch ${DEPS_DIR}/cmake-${CMAKE_VERSION}/cached
      fi
      export PATH="${DEPS_DIR}/cmake-${CMAKE_VERSION}/bin:${PATH}"
    fi
  - |
    if [ -f ${DEPS_DIR}/gtest-${GTEST_VERSION}/cached ]; then
      echo "Using chached gtest version ${GTEST_VERSION}."
    else
      GTEST_URL="https://github.com/google/googletest/archive/release-1.8.0.tar.gz"
      mkdir -p ${DEPS_DIR}/gtest-${GTEST_VERSION}
      travis_retry wget --no-check-certificate --quiet -O - "${GTEST_URL}" | tar --strip-components=1 -xz -C ${DEPS_DIR}/gtest-${GTEST_VERSION}
      touch ${DEPS_DIR}/gtest-${GTEST_VERSION}/cached
    fi
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CXX & $CXX --version

install:
  - mkdir -p build
  - mkdir -p build/gtest-${GTEST_VERSION}/$BUILD_TYPE
  - set +e; cd build/gtest-${GTEST_VERSION}/$BUILD_TYPE; set -e; pwd
  - cmake ${DEPS_DIR}/gtest-${GTEST_VERSION} -DBUILD_GMOCK=OFF -DBUILD_GTEST=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/external -DCMAKE_CXX_STANDARD=$CPPSTD
  - make -j 2
  - make install
  - set +e; cd ${TRAVIS_BUILD_DIR}/build; set -e; pwd
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=${DEPS_DIR}/external -DCMAKE_CXX_STANDARD=$CPPSTD
  - cat CMakeFiles/CMakeError.log || true
  - cat CMakeFiles/CMakeOutput.log || true
  - make -j2
  #- ctest -VV --timeout 10

script:
  - export OMP_NUM_THREADS=4
  - ctest -VV --timeout 10