language: cpp
sudo: true
script: cmake

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_VERSION="3.2.0"
    - GTEST_VERSION="1.8.1"

cache:
  directories:
    - ${DEPS_DIR}/cmake-${CMAKE_VERSION}

matrix:
  include:
    - env: GCC_VERSION=6 BUILD_TYPE=Debug CPP=14
      os: linux
      addons: &gcc6
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - env: GCC_VERSION=6 BUILD_TYPE=Release CPP=14
      os: linux
      addons: *gcc6

before_install:
  - set -e
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      if [ -f ${DEPS_DIR}/cmake-${CMAKE_VERSION}/cached ]; then
        echo "Using cached cmake version ${CMAKE_VERSION}."
      else
        CMAKE_URL="https://cmake.org/files/v3.2/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake-${CMAKE_VERSION}
        travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake-${CMAKE_VERSION}
        touch ${DEPS_DIR}/cmake-${CMAKE_VERSION}/cached
      fi
      export PATH="${DEPS_DIR}/cmake-${CMAKE_VERSION}/bin:${PATH}"
      if [ -f ${DEPS_DIR}/gtest-${GTEST_VERSION}/cached ]; then
        echo "Using chached gtest version ${GTEST_VERSION}."
      else
        GTEST_URL="https://github.com/google/googletest/archive/release-1.8.1.tar.gz"
        mkdir -p ${DEPS_DIR}/gtest-${GTEST_VERSION}
        travis_retry wget --no-check-certificate --quiet -O - "${GTEST_URL}" | tar --strip-components=1 -xz -C ${DEPS_DIR}/gtest-${GTEST_VERSION}
        touch ${DEPS_DIR}/gtest-${GTEST_VERSION}/cached
        mkdir -p ${DEPS_DIR}/gtest-${GTEST_VERSION}/cached/build
        cd ${DEPS_DIR}/gtest-${GTEST_VERSION}/cached/build
        cmake ..
        make
        make install
        cd ${TRAVIS_BUILD_DIR}
      fi
    fi
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

install:
  - mkdir -p build
  - set +e; cd build; set -e; pwd
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cat CMakeFiles/CMakeError.log || true
  - cat CMakeFiles/CMakeOutput.log || true
  - make -j2 VERBOSE=1
  - make test